# Generated by Django 5.2.6 on 2025-10-28 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='연도')),
                ('total_sales_units', models.IntegerField(default=0, verbose_name='총 판매 권수')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='총 매출')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annual_performance', to='book.author')),
            ],
            options={
                'verbose_name': '연간 실적',
                'verbose_name_plural': '연간 실적 목록',
                'ordering': ['-year'],
                'unique_together': {('author', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settlement_year', models.IntegerField(default=2025, verbose_name='정산 연도')),
                ('is_settled', models.BooleanField(default=False, verbose_name='정산 완료 여부')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='book.author', verbose_name='저자')),
            ],
            options={
                'verbose_name': '정산 기록',
                'verbose_name_plural': '정산 기록 목록',
                'ordering': ['-settlement_year', 'author__name'],
                'unique_together': {('author', 'settlement_year')},
            },
        ),
    ]
