# Generated by Django 5.2.6 on 2025-11-26 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
        ('reimbursement', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='settlement',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='settlement',
            name='author',
        ),
        migrations.CreateModel(
            name='RoyaltySettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold_met_year', models.IntegerField(default=2025, verbose_name='임계값 달성 연도')),
                ('threshold_multiple', models.PositiveIntegerField(verbose_name='달성 1000권 배수 (n)')),
                ('is_paid', models.BooleanField(default=False, verbose_name='정산 지급 완료 여부')),
                ('settlement_date', models.DateField(blank=True, null=True, verbose_name='실제 정산 지급일')),
                ('cumulative_sales_at_settlement', models.PositiveIntegerField(default=0, verbose_name='정산 시점의 누적 판매량')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='book.book', verbose_name='정산 대상 책')),
                ('composer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='book.composer', verbose_name='정산 대상 작곡가')),
            ],
            options={
                'verbose_name': '저작권 정산 내역',
                'verbose_name_plural': '저작권 정산 내역 목록',
                'ordering': ['-created_at'],
                'unique_together': {('book', 'composer', 'threshold_met_year', 'threshold_multiple')},
            },
        ),
        migrations.CreateModel(
            name='SaleRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateField(verbose_name='판매 날짜')),
                ('quantity_sold', models.PositiveIntegerField(default=0, verbose_name='판매 수량')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='판매 금액')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='기록 생성일')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_records', to='book.book', verbose_name='책')),
            ],
            options={
                'verbose_name': '판매 기록',
                'verbose_name_plural': '판매 기록 목록',
                'ordering': ['-sale_date'],
                'unique_together': {('book', 'sale_date')},
            },
        ),
        migrations.DeleteModel(
            name='AnnualPerformance',
        ),
        migrations.DeleteModel(
            name='Settlement',
        ),
    ]
