# Generated by Django 5.2.6 on 2025-09-17 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category1', models.CharField(max_length=100, verbose_name='category1')),
                ('category2', models.CharField(max_length=100, verbose_name='category2')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_korean', models.CharField(max_length=200, verbose_name='title_korean')),
                ('title_original', models.CharField(blank=True, max_length=200, null=True, verbose_name='title_original')),
                ('price', models.IntegerField(verbose_name='price')),
                ('book_type', models.CharField(choices=[('GEN', '일반'), ('PCS', '피스'), ('SCO', '총보')], default='GEN', max_length=3, verbose_name='book_type')),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True, verbose_name='subtitle')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.author', verbose_name='author_name')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.category', verbose_name='category')),
            ],
        ),
    ]
