# Generated by Django 5.2.6 on 2025-10-21 08:37

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category1', models.CharField(max_length=100, verbose_name='대분류')),
                ('category2', models.CharField(max_length=100, verbose_name='소분류')),
            ],
        ),
        migrations.CreateModel(
            name='Composer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='작곡가 이름')),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='연락처')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='생년월일')),
            ],
            options={
                'verbose_name': '작곡가',
                'verbose_name_plural': '작곡가 목록',
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='저자 이름')),
                ('contact_number', models.CharField(blank=True, max_length=20, verbose_name='연락처')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='생년월일')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '저자',
                'verbose_name_plural': '저자 목록',
            },
        ),
        migrations.CreateModel(
            name='AuthorWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.author', verbose_name='저자')),
            ],
            options={
                'verbose_name': '저자 작업',
                'verbose_name_plural': '저자 작업 목록',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_korean', models.CharField(max_length=200, verbose_name='책 제목 (한글)')),
                ('title_original', models.CharField(blank=True, max_length=200, null=True, verbose_name='책 제목 (원제)')),
                ('book_type', models.CharField(choices=[('GEN', '일반'), ('PCS', '피스'), ('SCO', '총보')], default='GEN', max_length=3, verbose_name='책 종류')),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True, verbose_name='부제')),
                ('publication_date', models.DateField(default=datetime.date.today, verbose_name='출판일')),
                ('publisher', models.CharField(default='와이즈성가', max_length=100, verbose_name='출판사')),
                ('authors', models.ManyToManyField(related_name='books', through='book.AuthorWork', to='book.author', verbose_name='저자')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.category', verbose_name='카테고리')),
            ],
        ),
        migrations.AddField(
            model_name='authorwork',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book', verbose_name='책'),
        ),
        migrations.CreateModel(
            name='ComposerWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_songs', models.PositiveIntegerField(default=1, verbose_name='곡 수')),
                ('royalty_percentage', models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='저작권료 (%)')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book', verbose_name='책')),
                ('composer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.composer', verbose_name='작곡가')),
            ],
            options={
                'verbose_name': '작곡가 작업',
                'verbose_name_plural': '작곡가 작업 목록',
                'unique_together': {('composer', 'book')},
            },
        ),
        migrations.AddField(
            model_name='book',
            name='composers',
            field=models.ManyToManyField(related_name='composed_books', through='book.ComposerWork', to='book.composer', verbose_name='작곡가'),
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='가격')),
                ('price_updated_at', models.DateTimeField(verbose_name='가격 변경일')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_histories', to='book.book', verbose_name='책')),
            ],
            options={
                'ordering': ['-price_updated_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='authorwork',
            unique_together={('author', 'book')},
        ),
    ]
