# Generated by Django 5.2.6 on 2025-10-28 06:37

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='저자 이름')),
            ],
            options={
                'verbose_name': '저자',
                'verbose_name_plural': '저자 목록',
            },
        ),
        migrations.CreateModel(
            name='Composer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='작곡가 이름')),
                ('date_of_birth', models.DateField(default=datetime.date(1900, 1, 1), verbose_name='생년월일')),
                ('contact_number', models.CharField(default='', max_length=20, verbose_name='연락처')),
            ],
            options={
                'verbose_name': '작곡가',
                'verbose_name_plural': '작곡가 목록',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_type', models.CharField(choices=[('GEN', '일반'), ('PCS', '피스'), ('SCO', '총보')], default='GEN', max_length=3, verbose_name='책 종류')),
                ('category1', models.CharField(blank=True, max_length=100, null=True, verbose_name='대분류')),
                ('category2', models.CharField(blank=True, max_length=100, null=True, verbose_name='소분류')),
                ('publisher', models.CharField(blank=True, max_length=100, null=True, verbose_name='출판사')),
                ('title_korean', models.CharField(max_length=200, verbose_name='책 제목 (한글)')),
                ('title_original', models.CharField(blank=True, max_length=200, null=True, verbose_name='책 제목 (원제)')),
                ('authors', models.ManyToManyField(blank=True, related_name='books', to='book.author', verbose_name='저자')),
            ],
            options={
                'verbose_name': '책',
                'verbose_name_plural': '책 목록',
            },
        ),
        migrations.CreateModel(
            name='ComposerWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_songs', models.PositiveIntegerField(default=1, verbose_name='곡 수')),
                ('royalty_percentage', models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='저작권료 (%)')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book', verbose_name='책')),
                ('composer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.composer', verbose_name='작곡가')),
            ],
            options={
                'verbose_name': '작곡가 작업',
                'verbose_name_plural': '작곡가 작업 목록',
                'unique_together': {('composer', 'book')},
            },
        ),
        migrations.AddField(
            model_name='book',
            name='composers',
            field=models.ManyToManyField(blank=True, related_name='composed_books', through='book.ComposerWork', to='book.composer', verbose_name='작곡가'),
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='가격')),
                ('price_updated_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='가격 변경일')),
                ('is_latest', models.BooleanField(default=False, verbose_name='최신 가격 여부(T/F)')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_histories', to='book.book', verbose_name='책')),
            ],
            options={
                'verbose_name': '가격 이력',
                'verbose_name_plural': '가격 이력 목록',
                'ordering': ['-price_updated_at'],
            },
        ),
    ]
