# Generated by Django 5.2.6 on 2025-09-23 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='price',
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='book.author', verbose_name='author_name'),
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='price')),
                ('price_updated_at', models.DateTimeField(verbose_name='price_updated_at')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_histories', to='book.book', verbose_name='book')),
            ],
            options={
                'ordering': ['-price_updated_at'],
            },
        ),
    ]
