# Generated by Django 5.2.6 on 2025-09-24 02:44

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_remove_book_price_alter_book_author_pricehistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Author', 'verbose_name_plural': 'Author_list'},
        ),
        migrations.AddField(
            model_name='author',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='contact_number'),
        ),
        migrations.AddField(
            model_name='author',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='date_of_birth'),
        ),
        migrations.AddField(
            model_name='book',
            name='publication_date',
            field=models.DateField(default=datetime.date.today, verbose_name='publication_date'),
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.category', verbose_name='category'),
        ),
        migrations.CreateModel(
            name='AuthorWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_songs', models.PositiveIntegerField(default=1, verbose_name='number_of_songs')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.author', verbose_name='author')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book', verbose_name='book')),
            ],
            options={
                'verbose_name': 'AuthorWork',
                'verbose_name_plural': 'AuthorWork_list',
                'unique_together': {('author', 'book')},
            },
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(related_name='books', through='book.AuthorWork', to='book.author', verbose_name='Authors'),
        ),
    ]
