# Generated by Django 5.2.6 on 2025-11-05 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='결제 완료일'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CARD', '카드'), ('BANK', '계좌 이체'), ('VISIONBOOK', '비전북'), ('ETC', '기타')], default='CARD', max_length=10, verbose_name='결제 방법'),
        ),
    ]
