# Generated by Django 5.2.6 on 2025-11-11 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_payment_date_order_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='additional_item',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='additional_price',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='additional_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='제본 수량'),
        ),
    ]
